### ISSUE TITLE
Redesign homepage

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanillaframework.io-design#15]
### Things to consider
- [x] Relook at components used and update accordingly
- [x] New _Suru_ folds
- [x] Vanilla react is no longer a project
- [x] Subscribe?
- [x] Downloads to now be Resources

**Comment by kwm14** [comment]
Add new '[What's new](https://github.com/canonical-web-and-design/design-vanillaframework.io/issues/13#issuecomment-537418629)' section to the newly proposed homepage design 👍

**Comment by kwm14** [comment]
## Hero exploration
- Applying new Suru templates
- Flipped gradient horizontally to showcase more orange #ubuntu for the time being...
  - New discussions on a color palette for Vanilla at Brand sprint 👍 

### 001
- Suru pullup strip
- Replicating content already existing on https://vanillaframework.io/

![hero-001](https://user-images.githubusercontent.com/17748020/66136799-f9aa1e00-e5f3-11e9-91e7-8ff7fc848e2c.png)

### 002
- Suru background image strip
- Image is a placeholder 😉 

![hero-002](https://user-images.githubusercontent.com/17748020/66136841-0890d080-e5f4-11e9-899a-0578022d9abc.png)

### 003
- Suru default strip
- Added an icon (placeholder) to get an idea whether it's whether investing in icon design

![hero-003](https://user-images.githubusercontent.com/17748020/66136863-10507500-e5f4-11e9-9959-7174c1a81d68.png)

**Comment by kwm14** [comment]
Add new '[Resources](https://github.com/canonical-web-and-design/vanillaframework.io/issues/238#issuecomment-537976727)' section to the newly proposed homepage design 👍

**Comment by kwm14** [comment]
## Initial exploration
- Adding new [Resources](https://github.com/canonical-web-and-design/vanillaframework.io/issues/238#issuecomment-537976727) and [What's new](https://github.com/canonical-web-and-design/design-vanillaframework.io/issues/13#issuecomment-537418629) sections
- On review for a first pass 001 - Suru pull strip seems the best option for the hero background
  - As we don't have any stock photography or iconography yet
- Added new blog section as seen on https://ubuntu.com/
- Left all sections white for the time being, until we decide on a color palette to use
  - Could we use default grey for the time being? `#f7f7f7`
- @spencerbygraves any thoughts?

### 001
![Global-homepage-001](https://user-images.githubusercontent.com/17748020/66217448-368f1700-e6bf-11e9-897c-5517d5c78174.png)

**Comment by spencerbygraves** [comment]
@kwm14 I'd also try a version with grey angled sections, we can have another look in the design review on Thursday.

**Comment by kwm14** [comment]
> @kwm14 I'd also try a version with grey angled sections, we can have another look in the design review on Thursday.

Ok great! I will update the sections to use grey 👍

**Comment by kwm14** [comment]
## Updated design
- Adding default grey `#f7f7f7` to sections
- Added **What's new** section below **Resources**
- Will review with _Designers_ on Thursday in Design review

### 002
![Global-homepage-002](https://user-images.githubusercontent.com/17748020/66843716-171ca780-ef65-11e9-932e-873dbc347cde.png)

**Comment by kwm14** [comment]
## Design review
_Full meetings notes https://github.com/canonical-web-and-design/meeting-notes/issues/453_ 

- Hero fold needs to have `64px` padding-top and bottom
- Degree angle doesn't look right, nudge left side down slightly
- Can we move the 'Get started' button inline with the second line? Explore
- Ubuntu Web Team > Canonical Web Team
- Colors look good in the gradient but maybe to close to u.com/canonical
- As Vanilla's brand color is `#333` should we use that? Explore with the Suru work planned for this iteration
- Section suru folds look good
- Should this be put into Vanilla? The debate continues...
- Who's using Vanilla - can we surface logos from showcase page rather than all Canonical products

**Comment by kwm14** [comment]
## Design update
- Updated design based on comments above
- In regards to the color gradient, I will be making further development when I define [Suru templates colors](https://app.zenhub.com/workspace/o/canonical-web-and-design/design-vanilla-framework/issues/427) next week, so it's just a placeholder now 
- So I just need review and sign-off on the page template @spencerbygraves 😄 

### 003
![Global-homepage-003](https://user-images.githubusercontent.com/17748020/67381515-ee5b6a00-f583-11e9-8245-c5bc6753aefd.png)

**Comment by spencerbygraves** [comment]
@kwm14 👍

**Comment by kwm14** [comment]
Design and discussion added to build [issue](https://github.com/canonical-web-and-design/vanillaframework.io/issues/255) 💯
