### ISSUE TITLE
Edit new pictogram colour to grey to use in homepage hero row

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanillaframework.io-design#2]
- Lightweight
- Extendable
- Open source

**Comment by yaili** [comment]
Based on dark grey pictograms that Matthieu had done previously, I changed the colour of the aubergine/orange pictograms (the 3 pictograms in the hero row) that he created for Vanilla, so they're more in line with our visual style. The Quick start and Guidelines rows will also have an image.

![vf io v19](https://user-images.githubusercontent.com/223966/27539846-fe15ae70-5a75-11e7-9a3b-b38c8cd06cd4.png)

**Comment by anthonydillon** [comment]
If this is the approved icons for the homepage please create a PR replacing the homepage design in code with this version. Once approved by someone then it can be merged and this issue will be closed. 

Could you please also [create an issue in the vanillaframework.io repo](https://github.com/canonical-websites/vanillaframework.io/issues/new) to build the icons in.

**Comment by barrymcgee** [comment]
@yaili @spencerbygraves Where can I find these pictogram assets please?

**Comment by yaili** [comment]
- Extendable: https://assets.ubuntu.com/v1/ba665746-pictogram_extension01-dark.svg
- Lightweight: https://assets.ubuntu.com/v1/fe40dc6a-pictogram_lightweight01b-dark.svg
- Open source: https://assets.ubuntu.com/v1/bcf3db83-pictogram_opensource01-dark.svg
