### ISSUE TITLE
Make ways to contribute more visible

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanillaframework.io-design#5]

**Comment by anthonydillon** [comment]
@kwm14 do you have any plan for this work?

**Comment by kwm14** [comment]
@anthonydillon I'm hoping to review CrazyEgg report that's been running on vf.io next iteration, so I can then see how our 'Contribute' page is working and to determine whether we need to update/move it.

Alternatively posting recent Tweets of bugs and using GitHub's new labels is a great way of getting the community to contribute more.

**Comment by kwm14** [comment]
We've created a new page https://vanillaframework.io/contribute and hope that this drives more contributors, which I will continue to monitor performance in GA 👍
