### ISSUE TITLE
Promote using Codepens to prototype with Vanilla

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanillaframework.io-design#6]

**Comment by kwm14** [comment]
Greg proposed using Codepen in his documentation work https://github.com/ubuntudesign/vanilla-and-base-squad/issues/24. But further conversations in the working group we agreed:

> We won't do CodePen examples, for now

If we decide in the future to add Codepen examples to our documentation or even vanillaframework.io with plans to add template examples I will create a new issue 👍
